In [4]:
def add_matrices(a,b):
    print(f"Input are : {a} , {b}")
    if len(a) == len(b):
        out_matrix = []
        for i in range(len(a)):
            if len(a[i]) == len(b[i]):
                out_matrix.append([])
                for j in range(len(a[i])):
                    out_matrix[i].append(a[i][j]+b[i][j])
            else:
                print("Both matrices must contains same number of rows and columns")
    else:
        print("Both matrices must contains same number of rows and columns")
    print(f"Output : {out_matrix}")
    

add_matrices([[1,2,3,4],[2,3,4,5],[3,4,5,6]],[[5,6,7,8],[6,7,8,9],[3,4,5,6]])

Input are : [[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]] , [[5, 6, 7, 8], [6, 7, 8, 9], [3, 4, 5, 6]]
Output : [[6, 8, 10, 12], [8, 10, 12, 14], [6, 8, 10, 12]]


In [7]:
a= [[2,3,4],[4,5,6],[2,5,8]]
b=[[1,4,2],[3,6,9],[2,4,7]]

def multiply_matrice(a,b):
    output = []
    if len(a[0]) == len(b):
        for x in range(len(a[0])):
            output.append([0 for y in range(len(b[0]))])
        for i in range(len(a)):
            for j in range(len(b[0])):
                for k in range(len(b)):
                    output[i][j] = output[i][j] + a[i][k]*b[k][j]
        print(output)
    else:
        print("Matrix multiplication is not possible")
        
multiply_matrice(a,b)

[[19, 42, 59], [31, 70, 95], [33, 70, 105]]


In [8]:
import numpy as np

def gen_transpose(matrix):
    out_matrix = []
    for x in range(len(matrix[0])):
        out_matrix.append([0 for y in range(len(matrix)) ])
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            out_matrix[i][j] = matrix[j][i]
    print(f"{matrix} matrix transpose is {out_matrix}")
    
gen_transpose(np.array([[2,3,4],[5,7,9],[1,6,3]]))

[[2 3 4]
 [5 7 9]
 [1 6 3]] matrix transpose is [[2, 5, 1], [3, 7, 6], [4, 9, 3]]


In [13]:
def  sortstr():
    string = input("Enter a string : ")
    sorted_string = sorted(string)
    print(sorted_string)
    final = "".join(sorted_string)
    print(final)
    
sortstr()

Enter a string : charvee
['a', 'c', 'e', 'e', 'h', 'r', 'v']
aceehrv


In [15]:
def removing_punctuations():
    punctuation = '''!@#$%^&*(){}[],.<>_+=~`'":;'''
    string = input("Enter a string :")
    output_string = " "
    for i in string:
        if i not in punctuation:
            output_string = output_string+i
    print(output_string)
    
removing_punctuations()

Enter a string :kjdhkj&jegdfs$sdj^kjdgfh@jhgdehj!med
 kjdhkjjegdfssdjkjdgfhjhgdehjmed
